receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318
        
exporters:
  prometheus:
    endpoint: otel-collector:8889
    
processors:
  batch:
    
extensions:
  health_check:
    endpoint: otel-collector:13133
    
service:
  extensions: [health_check]
  pipelines:
    metrics: 
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
      