global:
  scrape_interval: 10s
  
scrape_configs: 
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['localhost:9090']
      - targets: ['localhost:4317']
      - targets: ['localhost:4318']
  - job_name: 'otel-collector'
    static_configs: 
      - targets: ['otel-collector:8888']